# Generated by Django 5.2.18 on 2026-10-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_preventive_maintenance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workorder',
            new_name='operations__status_78f3fc_idx',
            old_name='operations__status_33d17f_idx',
        ),
    ]
